version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '09:00'
      timezone: 'Europe/London'
    commit-message:
      prefix: '⬆️'
      include: 'scope'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
    versioning-strategy: increase